"use strict";
console.log('Hellow world');
console.log('Thank you Governor sindh Kamran Tessori');
console.log('This is our first class today');
let userName = "22 + 33 + 4";
console.log(userName);
let userName1 = 22 + 33 + 4;
console.log(userName1);
let username3 = 'ALINA';
let username4 = 'username3';
let password = 123;
console.log(username4 == 'Alina');
console.log(password == 123);
